---
title: "Logistic-LASSO"
author: "Christian Pascual"
date: "4/29/2019"
output: html_document
---

```{r}
set.seed(8106)
library(tidyverse)
library(visdat)
library(caret)
mice = read_csv('./data.csv') %>% 
  mutate(MouseID = 1:length(MouseID))

final.mice = mice %>% 
  filter(!(MouseID %in% c(988, 989, 990))) %>% 
  select_if(function(col) !any(is.na(col))) %>% 
  select(DYRK1A_N:Genotype) %>% 
  mutate(
    genotype = ifelse(Genotype == "Control", "Control", "DS"),
    genotype = as.factor(genotype)
    ) %>% 
  select(-Genotype)

proteins = final.mice %>% 
  select(DYRK1A_N:CaNA_N) %>% 
  map_df(.x = ., function(col) (col - mean(col))/sd(col))

final.mice = cbind(proteins, genotype = final.mice$genotype)

proteins = final.mice %>% select(-genotype)
pca = prcomp(proteins)
reduced.pca.mice = as_tibble(cbind(pca$x[,1:27], genotype = final.mice$genotype)) %>% 
  mutate(
    genotype = ifelse(genotype == 1, "Control", "DS"),
    genotype = as.factor(genotype)
    )

train.idx = createDataPartition(final.mice$genotype, p = 0.80, list = FALSE, times = 1)
train = final.mice[train.idx,]
test = final.mice[-train.idx,]
pca.train = reduced.pca.mice[train.idx,]
pca.test = reduced.pca.mice[-train.idx,]
```

```{r}
trainControl = trainControl(method = "cv", number = 10, classProbs = TRUE)

modelFit = train(genotype ~ ., data = train, 
                 method = "glmnet", 
                 trControl = trainControl,
                 family = "binomial",
                 tuneGrid = expand.grid(.alpha = 1, .lambda = exp(seq(-8, -2, length.out = 100))))

pca.modelFit = train(genotype ~ ., data = pca.train, 
                     method = "glmnet", 
                     trControl = trainControl,
                     family = "binomial",
                     tuneGrid = expand.grid(.alpha = 1, .lambda = exp(seq(-8, -2, length.out = 100))))
```

```{r}
plot(modelFit)
```


```{r}
preds = predict(modelFit$finalModel, newx = test.data[,-ncol(test)])
```


